import Head from "next/head";
import styles from "@/styles/Home.module.css";


export default function Sec() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
          <h3>new page inside sec</h3>
      </main>
    </>
  );
}
